# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jtorecilla
tagline:          'A Jekyll theme'
description:      'The english version of my blog '
url:              https://github.com/Jtorrecilla/jtorrecilla.github.io
baseurl:          /

author:
  name:           'Javier Torrecilla'
  url:            https://twitter.com/jtorrecilla

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Jtorrecilla/jtorrecilla.github.io
